# Generated by Django 5.1.2 on 2024-10-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='background_gradient',
            field=models.CharField(default='background: linear-gradient(to right, #0f0c29, #302b63, #24243e', max_length=100),
        ),
    ]
