# Generated by Django 5.1.2 on 2024-10-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_projectlink_projectstat_project_links_project_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlink',
            name='name',
        ),
        migrations.AddField(
            model_name='projectlink',
            name='url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
