# Generated by Django 5.1.2 on 2024-10-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_projectstat_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstat',
            name='label',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
