# Generated by Django 5.1.2 on 2024-10-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_projectstat_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('job_role', models.CharField(max_length=50)),
                ('employment_period', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
