# Generated by Django 5.1.2 on 2024-10-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
