# Generated by Django 5.1.2 on 2024-10-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_project_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_img',
            field=models.ImageField(null=True, upload_to='project-cover/'),
        ),
    ]
